development:
  dialect: postgres
  datasource: host=${POSTGRESQL_DB} dbname=${POSTGRESQL_DB} user=${POSTGRESQL_USER} password=${POSTGRESQL_PASSWORD} sslmode=disable
  dir: migrations
  table: migrations